'use client';
import React, { useState } from 'react';
import { useVendor } from '@/context/useVendorStore';
import { KeyRound, ShieldAlert, LogOut } from 'lucide-react';

export const ActivationView: React.FC = () => {
  const { sessionUser, claimAccessToken, signOut } = useVendor();
  const [token, setToken] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setLoading(true);

    try {
      if (!token.trim()) throw new Error('Please enter a license access token.');
      
      const success = await claimAccessToken(token.trim());
      if (!success) {
        throw new Error('This license token is invalid or has already been used.');
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Token verification failed.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex-1 overflow-y-auto px-6 py-8 flex flex-col justify-center bg-[#0a0a0a] text-white no-scrollbar select-none">
      <div className="w-full max-w-sm mx-auto space-y-6">
        
        {/* Lock Screen Icon */}
        <div className="text-center space-y-2">
          <div className="inline-flex p-3 bg-red-500/10 text-red-400 rounded-full border border-red-500/20 shadow-lg shadow-red-500/5">
            <ShieldAlert size={36} className="animate-pulse" />
          </div>
          <h2 className="text-2xl font-black mt-2 tracking-tight">License Required</h2>
          <p className="text-xs text-slate-400 leading-relaxed max-w-xs mx-auto">
            You are logged in as <span className="font-bold text-slate-200">{sessionUser?.email}</span> but your profile has no active store license.
          </p>
        </div>

        {/* Form Card */}
        <div className="bg-[#121212]/80 backdrop-blur-md border border-slate-800/80 rounded-3xl p-5 shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 left-1/4 w-1/2 h-[1px] bg-gradient-to-r from-transparent via-[#FF6B35]/50 to-transparent"></div>
          
          <form onSubmit={handleSubmit} className="space-y-4">
            {error && (
              <div className="flex gap-2 p-3 bg-red-500/10 border border-red-500/20 text-red-400 rounded-2xl text-[11px] font-bold leading-normal">
                <span>⚠️ {error}</span>
              </div>
            )}

            <div className="space-y-1.5">
              <label className="text-[9px] uppercase font-black text-slate-450 tracking-wider">License Access Token</label>
              <div className="relative">
                <KeyRound size={14} className="absolute left-3 top-2.5 text-slate-500" />
                <input
                  type="text"
                  value={token}
                  onChange={e => setToken(e.target.value)}
                  placeholder="e.g. TEST-TOKEN-123"
                  className="w-full bg-[#161616] border border-slate-800/80 rounded-xl pl-9 pr-3 py-2 text-xs font-bold text-white focus:outline-none focus:border-[#FF6B35] placeholder:text-slate-650 transition font-mono uppercase"
                  required
                />
              </div>
              <p className="text-[9px] text-slate-500 font-semibold leading-relaxed mt-1">
                Enter the access token generated by your administrator to activate and link this account to a store.
              </p>
            </div>

            {/* Activate Button */}
            <button
              type="submit"
              disabled={loading}
              className="w-full py-2.5 rounded-2xl bg-gradient-to-tr from-[#FF6B35] to-[#FFB347] text-white font-extrabold text-xs shadow-md shadow-orange-500/10 active:scale-[0.98] transition focus:outline-none disabled:opacity-50 mt-1 flex items-center justify-center gap-2"
            >
              {loading ? (
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
              ) : (
                'Activate Store Account 🔑'
              )}
            </button>
          </form>
        </div>

        {/* Switch Account / Logout Action */}
        <div className="flex justify-center">
          <button
            onClick={signOut}
            className="flex items-center gap-1.5 py-2 px-4 rounded-xl text-xs font-bold text-slate-400 hover:text-white transition active:scale-95 bg-[#121212] border border-slate-800/80"
          >
            <LogOut size={13} />
            <span>Sign Out / Switch Account</span>
          </button>
        </div>

      </div>
    </div>
  );
};
